language: php

php:
  - 5.6
  - 7.0
  - 7.2
  - nightly

matrix:
  include:
    - php: 7.1
      env: COVERAGE=yes
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - travis_retry composer install

script:
  - if [[ $COVERAGE == yes ]]; then ./vendor/bin/codecept run --coverage-xml; else ./vendor/bin/codecept run; fi

after_script:
  - if [[ $COVERAGE == yes ]]; then ./vendor/bin/coveralls; fi
